<?php


/**
 * Implements hook_menu().
 *
 * Drupal menus allow urls to be used as function calls, giving Drupal gets much
 * of its power and flexibility.
 *
 * @see https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_menu/7
 */
function js_loader_menu() {
  return array(
    'admin/config/development/js_loader' => array(
      'title' => 'JS library loader',
      'description' => 'Configure JS loader module.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('js_loader_admin'),
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}



/**
 * Admin form.
 *
 * @param array $form
 *   An array representing a Drupal form.
 * @param array $form_state
 *   The Drupal form state.
 *
 * @return array
 *   Returns admin form.
 */
function js_loader_admin($form, &$form_state) {
  $form = array();

  $form['js_loader_library'] = array(
    '#type' => 'select',
    '#title' => t('JS library to be loaded'),
    '#options' => array(
      'flot' => t('Flot'),
      ),
    '#required' => TRUE,
    '#default_value' => variable_get('js_loader_library', ''),
    '#description' => t('JS library to be loaded, must be already installed in sites/all/libraries.'),
  );

   return system_settings_form($form);
}


/**
 * Implemets hook_init().
 */
function js_loader_init() {
  $lib = variable_get('js_loader_library', '');
  if (isset($lib)) {
     js_loader_add_js($lib);
  } else {
    drupal_set_message(t('The js library must be configured.'), 'error');
  }

}

/**
 * Load JS libraries.
 */
function js_loader_add_js($lib = 'flot') {

  $path = _js_loader_get_library_path($lib);
  $ie_support_tag = <<<EOL
  <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="{$path}/excanvas.min.js"></script><![endif]-->
EOL;
  if ($path) {
    $element = array(
    '#type' => 'markup',
    '#markup' => $ie_support_tag,
  );
  drupal_add_html_head($element, $lib);
  switch ($lib) {
    case 'flot' :
      $js_file = '/jquery.flot.js';
      break;
  }
  drupal_add_js($path . $js_file);
  } else {
    drupal_set_message(t('Cannot find the library %lib under sites/all/libraries directory', array('%lib' => $lib,)), 'error');
  }

}

function _js_loader_get_library_path($lib = '') {
  $path = '';
  if (module_exists('libraries') && libraries_get_path($lib)) {
    $path = libraries_get_path($lib);
  }
  return $path;
}
